[package]
name = "distributary"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

[features]
web = ["rustful", "rustc-serialize"]
b_memcached = ["memcache"]
b_postgresql = ["postgres", "r2d2", "r2d2_postgres"]
b_mysql = ["mysql", "r2d2", "r2d2_mysql"]
b_netsoup = ["futures", "tokio-core", "tarpc", "tarpc-plugins", "serde", "serde_derive"]

[dependencies]
itertools = "0.5"
petgraph = "0.4"
regex = "0.1"
fnv = "1.0"
chashmap = "0.1.2"

spmc = "0.2.1"
nom_sql = { git = "https://github.com/ms705/nom-sql.git" }

# for benchmarks
# cli
clap = "2.13"
# distributions
rand = "0.3"
# sampling
hdrsample = "2.1"
# postgresql
postgres = { version = "0.11", optional = true }
r2d2 = { version = "0.7", optional = true }
r2d2_postgres = { version = "0.10", optional = true }
# mysql
mysql = { version = "8.0", optional = true }
r2d2_mysql = { version = "8.0", optional = true }
# memcached
memcache = {git="https://github.com/aisk/rust-memcache.git", rev = "f2df617a8a7dec2dfcd4cda76002d8c10b993263", optional = true }
# netsoup
futures = { version ="0.1.9", optional = true }
tokio-core = { version = "0.1", optional = true }
tarpc = {git="https://github.com/google/tarpc.git", optional = true}
tarpc-plugins = { git = "https://github.com/google/tarpc", optional = true }
serde = { version = "0.9", optional = true }
serde_derive = { version = "0.9", optional = true }

# for web
rustful = { version = "0.9", optional = true }
rustc-serialize = { version = "0.3", optional = true }

[profile.release]
debug=true

[lib]
name = "distributary"
path = "src/lib.rs"

[[bin]]
name = "web"
path = "src/web/main.rs"

[[bin]]
name = "web_sql"
path = "src/web/sql_main.rs"

[[bin]]
name = "bank"
path = "benchmarks/bank.rs"

[[bin]]
name = "vote"
path = "benchmarks/vote.rs"
